#!/bin/zsh

# vim: ft=zsh sw=2 ts=2 et

if [[ -n "$JETBRAINS_PROJECT" ]] then
	cd "$JETBRAINS_PROJECT"
elif [[ -d ".idea" ]] then
	cd "$PWD"
elif [[ -n "$VSCODE_PROJECT_DIR" ]] then
	cd "$VSCODE_PROJECT_DIR"
else
	echo "No project found"
fi
