alias z="$ZDOTDIR"
alias d="$ZDOTDIR/zshrc.d"
alias cm="chezmoi"
alias ci="$EDITOR $(chezmoi source-path)/.chezmoiignore"
alias cmcd="cd $(chezmoi source-path)"

alias zshenv="$EDITOR $ZDOTDIR/.zshenv"
alias zshrc="$EDITOR $ZDOTDIR/.zshrc"
alias plugins="$EDITOR $ZDOTDIR/.zsh_plugins.txt"
alias aliases="$EDITOR $ZSH_CUSTOM/*aliases.zsh"
alias misc="$EDITOR $ZSH_CUSTOM/*misc.zsh"
alias vars="$EDITOR $ZSH_CUSTOM/*vars.zsh"
alias paths="$EDITOR $ZSH_CUSTOM/*path.zsh"
alias it2vars="$EDITOR $ZSH_CUSTOM/*iterm2_variables.zsh"
alias zld="cd $ZSH_CUSTOM/local/$(chezmoi data | jq -r .chezmoi.hostname)"
alias cat="bat"
alias pcat="bat -p"
alias more="bat --paging=always"
alias page="more"
alias rg="batgrep"
alias man="BAT_PAGING=always man"

alias ls="eza --icons"
alias ll="ls -lh"
alias la="ls -a"
alias lla="ls -lha"

alias up="cd .."
alias rm="rm -i"
alias r="exec zsh"
alias home="cd $HOME"
alias root="cd /"
alias img="imgcat"
alias path="echo $path"
alias python="uv run ~/.config/python/repl.py"
alias py="python"
alias pch="pre-commit"
alias exa="eza"
alias mkdir="mkdir -p"

alias -g -- --help="--help 2>&1 |  bat --plain --language help --paging always"
