alias z="$ZDOTDIR"
alias d="$ZDOTDIR/zshrc.d"
alias cm="chezmoi"
alias ci="$EDITOR $(chezmoi source-path)/.chezmoiignore"
alias cmcd="cd $(chezmoi source-path)"

alias zshenv="$EDITOR $ZDOTDIR/.zshenv"
alias zshrc="$EDITOR $ZDOTDIR/.zshrc"
alias plugins="$EDITOR $ZDOTDIR/.zsh_plugins.txt"
alias aliases="$EDITOR $ZSH_CUSTOM/*aliases.zsh"
alias misc="$EDITOR $ZSH_CUSTOM/*misc.zsh"
alias vars="$EDITOR $ZSH_CUSTOM/*vars.zsh"
alias paths="$EDITOR $ZSH_CUSTOM/*path.zsh"
alias it2vars="$EDITOR $ZSH_CUSTOM/*iterm2_variables.zsh"
alias zlocal="$EDITOR $ZSH_CUSTOM/99_local.zsh"
alias cat="bat"
alias pcat="bat -p"
alias more="bat --paging=always"
alias less="more"
alias page="more"

alias ls="eza --icons"
alias ll="ls -lh"
alias la="ls -a"
alias lla="ls -lha"

alias up="cd .."
alias rm="rm -i"
alias reload="exec zsh"
alias r="reload"
alias home="cd $HOME"
alias root="cd /"
alias img="imgcat"
alias path="echo $path"
alias python="uv run ~/.config/python/repl.py"
alias py="python"
alias pch="pre-commit"
alias exa="eza"
