[tools]
"aqua:micro-editor/micro" = "latest"
atuin = "latest"
bat = "latest"
direnv = "latest"
dotnet = "latest"
eza = "latest"
gh = "latest"
"github:charmbracelet/wishlist" = "latest"
glab = { version = "latest", exe = "glab" }
glow = "latest"
gum = "latest"
node = "latest"
pre-commit = "latest"
starship = "latest"
ttyd = "latest"
uv = "latest"
vhs = "latest"

[settings]

[settings.ruby]
compile = false
